apiVersion: v1
kind: Service
metadata:
  name: Helloworldpython-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: Helloworldpython
  ports:
    - port: 8080      
      targetPort: 8080      
      nodePort: 30007
